sql.add_friend=insert into friend(\
  name,surname,birth_date\
  ,date_met,description,status_id,gender_id) values(\
  ?,?,?,?,?,?,?)

sql.find_gender_by_title=select id from gender where title = ?
sql.find_status_by_title=select id from status where title = ?
sql.find_max_friend_id=select max(id) from friend

sql.update_friend_status=update friend set status_id = ? where id = ?

sql.id_friend_exists=select count(1) from friend where id = ?
sql.delete_friend=delete from friend where id = ?

sql.get_all_friends=select name,surname, birth_date, date_met, description\
,status.title as status \
,gender.title as gender \
from friend \
join gender on friend.gender_id = gender.id \
join status on friend.status_id = status.id


sql.get_all_statuses_titles=select title from status
sql.get_all_genders_titles=select title from gender